import { NavItem, Service, Review, TimelineItem } from '@/types';

export const SITE_CONFIG = {
  name: 'Sirajul',
  fullName: 'Sirajul Islam Sohag',
  title: 'Digital Marketing Consultant',
  description: 'Premium digital marketing consultant helping businesses generate leads, scale sales, and build their online presence through data-driven strategies.',
  email: 'sirajulislamshoag697@gmail.com',
  phone: '+880 1793859694',
  address: 'Dhaka, Bangladesh',
  calendlyUrl: process.env.NEXT_PUBLIC_CALENDLY_URL || 'https://calendly.com/siraj',
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || 'https://sirajmarketing.com',
} as const;

export const NAV_ITEMS: NavItem[] = [
  { label: 'Home', href: '/' },
  { label: 'About', href: '/about' },
  { label: 'Services', href: '/services' },
  { label: 'Portfolio', href: '/portfolio' },
  { label: 'Blog', href: '/blog' },
  { label: 'Contact', href: '/contact' },
];

export const TYPING_ROLES = [
  'Certified Google Ads Expert & PPC Consultant',
  'Google Ads Specialist',
  'Performance Marketer',
  'Marketing Strategist',
  'Growth Consultant',
];

export const ORBIT_SKILLS = [
  { label: 'Google Ads', iconUrl: 'https://cdn.simpleicons.org/googleads/4285F4', color: '#4285F4' },
  { label: 'Meta Ads', iconUrl: 'https://cdn.simpleicons.org/meta/0668E1', color: '#0668E1' },
  { label: 'Google Analytics', iconUrl: 'https://cdn.simpleicons.org/googleanalytics/F59E0B', color: '#F59E0B' },
  { label: 'SEO', iconUrl: 'https://cdn.simpleicons.org/google/22C55E', color: '#22C55E' },
  { label: 'Mailchimp', iconUrl: 'https://cdn.simpleicons.org/mailchimp/FFE01B', color: '#FFE01B' },
  { label: 'HubSpot', iconUrl: 'https://cdn.simpleicons.org/hubspot/FF7A59', color: '#FF7A59' },
];

export const STATS = [
  { label: 'Years Experience', value: 5, suffix: '+' },
  { label: 'Projects Completed', value: 200, suffix: '+' },
  { label: 'Happy Clients', value: 150, suffix: '+' },
  { label: 'Revenue Generated', value: 2.5, suffix: 'M+', prefix: '$' },
];

export const SERVICES: Service[] = [
  {
    id: 'google-ads',
    icon: 'Target',
    title: 'Google Ads Management',
    description: 'Data-driven Google Ads campaigns that maximize ROI. From Search to Performance Max, I optimize every dollar of your ad spend.',
    features: ['Search Campaigns', 'Performance Max', 'Display Network', 'YouTube Ads', 'Shopping Campaigns', 'Remarketing'],
  },
  {
    id: 'facebook-ads',
    icon: 'Megaphone',
    title: 'Facebook & Meta Ads',
    description: 'Strategic Facebook and Instagram advertising that reaches your ideal customers and drives conversions at scale.',
    features: ['Lead Generation', 'Conversion Campaigns', 'Retargeting', 'Lookalike Audiences', 'Creative Strategy', 'A/B Testing'],
  },
  {
    id: 'seo',
    icon: 'Search',
    title: 'SEO Optimization',
    description: 'Comprehensive SEO strategies that improve your organic rankings, drive qualified traffic, and build long-term visibility.',
    features: ['Technical SEO', 'On-Page Optimization', 'Content Strategy', 'Link Building', 'Local SEO', 'SEO Audits'],
  },
  {
    id: 'analytics',
    icon: 'BarChart3',
    title: 'Analytics & Tracking',
    description: 'Full-stack analytics setup with Google Analytics 4, Tag Manager, and conversion tracking for data-driven decisions.',
    features: ['GA4 Setup', 'GTM Implementation', 'Conversion Tracking', 'Custom Dashboards', 'Attribution Modeling', 'Data Analysis'],
  },
  {
    id: 'email-marketing',
    icon: 'Mail',
    title: 'Email Marketing',
    description: 'High-converting email campaigns and automation sequences that nurture leads and drive repeat purchases.',
    features: ['Campaign Strategy', 'Automation Flows', 'List Segmentation', 'A/B Testing', 'Template Design', 'Deliverability'],
  },
  {
    id: 'cro',
    icon: 'TrendingUp',
    title: 'Conversion Optimization',
    description: 'Data-backed CRO strategies that turn more visitors into customers through testing, analysis, and iterative improvements.',
    features: ['Landing Page Optimization', 'A/B Testing', 'Heat Map Analysis', 'User Journey Mapping', 'Funnel Optimization', 'UX Improvements'],
  },
];



export const TIMELINE_DATA: TimelineItem[] = [
  {
    year: '2024',
    title: 'Senior Marketing Consultant',
    company: 'Freelance',
    description: 'Managing $500K+ monthly ad spend across Google & Meta for international clients. Specializing in e-commerce scaling and lead generation.',
  },
  {
    year: '2023',
    title: 'Digital Marketing Manager',
    company: 'Growth Agency',
    description: 'Led a team of 5 marketers, managed 30+ client accounts, and achieved average 4.2x ROAS across all campaigns.',
  },
  {
    year: '2022',
    title: 'PPC Specialist',
    company: 'Digital Studio',
    description: 'Specialized in Google Ads and Facebook Ads management. Reduced client CAC by 45% through data-driven optimization.',
  },
  {
    year: '2021',
    title: 'Marketing Executive',
    company: 'Startup Inc.',
    description: 'Built marketing infrastructure from ground up. Launched successful campaigns across multiple channels driving 300% growth.',
  },
  {
    year: '2020',
    title: 'Digital Marketing Intern',
    company: 'Agency Pro',
    description: 'Started career in digital marketing, learning the fundamentals of PPC, SEO, and analytics while managing small campaigns.',
  },
];

export const REVIEWS: Review[] = [
  {
    id: 'rev-1',
    name: 'Roofing Company Owner',
    company: 'Roofing Services',
    role: 'Owner',
    photo: 'https://ui-avatars.com/api/?name=Roofing+Company&background=4F46E5&color=fff&size=100',
    rating: 5,
    date: 'Aug 16, 2026',
    text: 'We were getting very few quality calls from Google Ads, and our previous campaigns were wasting a lot of money. After the Google Ads setup and optimization, we started getting much better roofing leads and more calls from people actually looking for our services. The campaign structure and ongoing management made a huge difference.',
  },
  {
    id: 'rev-2',
    name: 'HVAC Business Owner',
    company: 'HVAC Solutions',
    role: 'Owner',
    photo: 'https://ui-avatars.com/api/?name=HVAC+Owner&background=06B6D4&color=fff&size=100',
    rating: 5,
    date: 'Aug 14, 2026',
    text: 'Our HVAC campaigns were running, but we weren\'t getting the results we expected. The Google Ads account was completely restructured, the keywords were cleaned up, and the targeting was improved. We started seeing more calls and better-quality leads without simply increasing the budget.',
  },
  {
    id: 'rev-3',
    name: 'Cleaning Company Owner',
    company: 'Cleaning Services',
    role: 'Owner',
    photo: 'https://ui-avatars.com/api/?name=Cleaning+Company&background=22C55E&color=fff&size=100',
    rating: 5,
    date: 'Aug 10, 2026',
    text: 'We needed more local cleaning customers, but our Google Ads were not generating enough leads. The new campaign setup was much more focused on the services and locations we actually wanted to target. Within a short time, we started receiving more calls and quote requests.',
  },
  {
    id: 'rev-4',
    name: 'Auto Detailing Business Owner',
    company: 'Auto Detailing Studio',
    role: 'Owner',
    photo: 'https://ui-avatars.com/api/?name=Auto+Detailing&background=F59E0B&color=fff&size=100',
    rating: 5,
    date: 'Aug 05, 2026',
    text: 'Our biggest problem was getting the right customers from Google. The campaign was rebuilt around high-intent keywords and specific services. Now we\'re getting more calls and inquiries from people who are actually looking for auto detailing instead of just random clicks.',
  },
  {
    id: 'rev-5',
    name: 'E-commerce Store Owner',
    company: 'E-commerce Brand',
    role: 'Store Owner',
    photo: 'https://ui-avatars.com/api/?name=Ecommerce+Store&background=8B5CF6&color=fff&size=100',
    rating: 5,
    date: 'Jul 29, 2026',
    text: 'Our Google Ads account had a lot of products but no clear strategy. The campaigns were reorganized, product groups were cleaned up, and the tracking was properly reviewed. We finally had a much clearer picture of what was actually driving sales and where our budget was going.',
  },
  {
    id: 'rev-6',
    name: 'Plumbing Company Owner',
    company: 'Plumbing & Drain Services',
    role: 'Company Owner',
    photo: 'https://ui-avatars.com/api/?name=Plumbing+Company&background=3B82F6&color=fff&size=100',
    rating: 5,
    date: 'Jul 22, 2026',
    text: 'We needed more emergency plumbing calls, especially from people searching for a plumber right away. The Google Ads campaigns were optimized around high-intent searches and our service areas. The quality of the calls improved, and we started seeing a much better return from our ad spend.',
  },
  {
    id: 'rev-7',
    name: 'Pest Control Business Owner',
    company: 'Pest Control Services',
    role: 'Business Owner',
    photo: 'https://ui-avatars.com/api/?name=Pest+Control&background=10B981&color=fff&size=100',
    rating: 5,
    date: 'Jul 15, 2026',
    text: 'Before working together, we were spending money on Google Ads but weren\'t sure which keywords or campaigns were actually producing customers. Everything was cleaned up and properly organized. Now we can see where our leads are coming from, and we\'re getting more relevant pest-control inquiries.',
  },
  {
    id: 'rev-8',
    name: 'Solar Company Owner',
    company: 'Solar Energy Solutions',
    role: 'Company Owner',
    photo: 'https://ui-avatars.com/api/?name=Solar+Energy&background=F97316&color=fff&size=100',
    rating: 5,
    date: 'Jul 08, 2026',
    text: 'Our solar campaigns needed a complete strategy, not just more keywords. The account was restructured, targeting was improved, and the ads were aligned with what potential customers were actually searching for. The result was better lead quality and a much more organized Google Ads account.',
  },
  {
    id: 'rev-9',
    name: 'Garage Door Company Owner',
    company: 'Garage Door Services',
    role: 'Company Owner',
    photo: 'https://ui-avatars.com/api/?name=Garage+Door&background=6366F1&color=fff&size=100',
    rating: 5,
    date: 'Jun 28, 2026',
    text: 'We wanted more calls from homeowners looking for garage door repair and installation. The campaigns were rebuilt around the services we wanted to grow, and unnecessary spending was reduced. We started receiving more relevant calls and quote requests from our target area.',
  },
  {
    id: 'rev-10',
    name: 'Landscaping Company Owner',
    company: 'Landscaping & Design',
    role: 'Company Owner',
    photo: 'https://ui-avatars.com/api/?name=Landscaping+Company&background=14B8A6&color=fff&size=100',
    rating: 5,
    date: 'Jun 19, 2026',
    text: 'Our previous Google Ads campaigns were getting clicks but not enough customers. The new setup focused much more on local intent, service-specific keywords, negative keywords, and conversion tracking. We\'re now getting more inquiries from people who are actually interested in our landscaping services.',
  },
  {
    id: 'rev-11',
    name: 'Dental Clinic Owner',
    company: 'Dental Practice',
    role: 'Clinic Owner',
    photo: 'https://ui-avatars.com/api/?name=Dental+Clinic&background=EC4899&color=fff&size=100',
    rating: 5,
    date: 'Jun 10, 2026',
    text: 'We wanted Google Ads to bring us more appointment requests, not just website traffic. The campaigns were optimized around high-intent searches and our most profitable services. The tracking also helped us understand which campaigns were actually generating appointments.',
  },
  {
    id: 'rev-12',
    name: 'Law Firm Owner',
    company: 'Legal Services Practice',
    role: 'Law Firm Owner',
    photo: 'https://ui-avatars.com/api/?name=Law+Firm&background=8B5CF6&color=fff&size=100',
    rating: 5,
    date: 'May 30, 2026',
    text: 'Google Ads can get expensive very quickly in the legal industry, so we needed someone who understood how to control wasted spend. The account was carefully structured, search terms were reviewed regularly, and the campaigns were optimized around high-intent searches. We started seeing better-quality inquiries from our target locations.',
  },
  {
    id: 'rev-13',
    name: 'Moving Company Owner',
    company: 'Relocation & Moving',
    role: 'Moving Company Owner',
    photo: 'https://ui-avatars.com/api/?name=Moving+Company&background=F59E0B&color=fff&size=100',
    rating: 5,
    date: 'May 18, 2026',
    text: 'We were spending money on Google Ads but receiving too many irrelevant inquiries. After the campaign restructuring, keyword targeting and negative keywords were much more focused. The number of useful calls increased, and we had fewer wasted clicks.',
  },
  {
    id: 'rev-14',
    name: 'Home Improvement Company Owner',
    company: 'Home Improvement Co.',
    role: 'Company Owner',
    photo: 'https://ui-avatars.com/api/?name=Home+Improvement&background=06B6D4&color=fff&size=100',
    rating: 5,
    date: 'May 04, 2026',
    text: 'We had tried Google Ads before, but the account never felt properly organized. The campaigns were rebuilt from the ground up with better targeting, ad copy, conversion tracking, and ongoing optimization. Now we have a much better system for generating leads and measuring results.',
  },
  {
    id: 'rev-15',
    name: 'Healthcare Business Owner',
    company: 'Medical & Healthcare',
    role: 'Healthcare Business Owner',
    photo: 'https://ui-avatars.com/api/?name=Healthcare+Business&background=EF4444&color=fff&size=100',
    rating: 5,
    date: 'Apr 25, 2026',
    text: 'We needed a reliable way to generate more appointment inquiries through Google. The campaigns were set up around our most important services and local search intent. The tracking and reporting also made it much easier to understand which campaigns were producing real business results.',
  },
  {
    id: '1',
    name: 'Alex Thompson',
    company: 'TechScale Inc.',
    role: 'CEO',
    photo: 'https://ui-avatars.com/api/?name=Alex+Thompson&background=4F46E5&color=fff&size=100',
    rating: 5,
    date: 'Aug 12, 2026',
    text: 'Sirajul transformed our Google Ads strategy completely. We went from burning $10K/month with no results to generating 5x ROAS within 60 days. His analytical approach is unmatched.',
  },
  {
    id: '2',
    name: 'Sarah Chen',
    company: 'BeautyBox',
    role: 'Founder',
    photo: 'https://ui-avatars.com/api/?name=Sarah+Chen&background=8B5CF6&color=fff&size=100',
    rating: 5,
    date: 'Jul 28, 2026',
    text: 'Working with Sirajul was a game-changer for our e-commerce brand. He scaled our Facebook Ads from $500/day to $5000/day while maintaining a profitable ROAS. Truly exceptional.',
  },
  {
    id: '3',
    name: 'Michael Roberts',
    company: 'LegalEase',
    role: 'Marketing Director',
    photo: 'https://ui-avatars.com/api/?name=Michael+Roberts&background=06B6D4&color=fff&size=100',
    rating: 5,
    date: 'Jun 15, 2026',
    text: 'Sirajul\'s SEO expertise helped us rank #1 for our most competitive keywords within 4 months. Our organic traffic increased by 340% and lead quality improved dramatically.',
  },
  {
    id: '4',
    name: 'Emily Park',
    company: 'FitLife',
    role: 'Co-Founder',
    photo: 'https://ui-avatars.com/api/?name=Emily+Park&background=22C55E&color=fff&size=100',
    rating: 5,
    date: 'Apr 27, 2026',
    text: 'The best marketing consultant we\'ve ever worked with. Sirajul doesn\'t just run ads — he builds entire growth systems. Our revenue tripled in 6 months.',
  },
  {
    id: '5',
    name: 'David Miller',
    company: 'PropTech Solutions',
    role: 'COO',
    photo: 'https://ui-avatars.com/api/?name=David+Miller&background=F59E0B&color=fff&size=100',
    rating: 5,
    date: 'May 20, 2026',
    text: 'Sirajul\'s data-driven approach to our PPC campaigns reduced our cost per lead by 62% while increasing lead volume by 180%. His weekly reports and optimization cadence are outstanding.',
  },
  {
    id: '6',
    name: 'Lisa Wang',
    company: 'EduTech Global',
    role: 'VP Marketing',
    photo: 'https://ui-avatars.com/api/?name=Lisa+Wang&background=EF4444&color=fff&size=100',
    rating: 5,
    date: 'Mar 10, 2026',
    text: 'From analytics setup to full-funnel campaign management, Sirajul handles everything with precision. He helped us build a marketing engine that now generates $200K+ monthly revenue.',
  },
];

export const TRUSTED_BRANDS = [
  { name: 'United Trailers', logo: '/logos/1785730667707_unitedtrailers_com_au_logo9_nobg.png' },
  { name: 'Peckphase', logo: '/logos/Peckphase_nobg.png' },
  { name: 'Anan Care Services', logo: '/logos/anancareservices_com_au_logo13_nobg.png' },
  { name: 'Asap Tars', logo: '/logos/asaptars_com_logo5_nobg.png' },
  { name: 'Drugstore Online', logo: '/logos/drugstoreonline_me_logo11_nobg.png' },
  { name: 'Engraved Anything', logo: '/logos/engravedanything_com_logo10_nobg.png' },
  { name: 'Fishing Tours', logo: '/logos/fishingtoursplayadelcarmen_com_logo13_nobg.png' },
  { name: 'Fresh Ausfluege', logo: '/logos/fresh_deutsche-ausfluege-mexiko_de_logo12_nobg.png' },
  { name: 'House of Appliances', logo: '/logos/houseofappliances_co_logo11_nobg.png' },
  { name: 'Leather Dot BD', logo: '/logos/leatherdotbd_com_logo5_nobg.png' },
  { name: 'Location Mobile Tire', logo: '/logos/locationmobiletire_com_logo9_nobg.png' },
  { name: 'Photo Reviser', logo: '/logos/photoreviser_com_logo84_nobg.png' },
  { name: 'Pirate Mobile', logo: '/logos/piratemobile_gg_logo15_nobg.png' },
  { name: 'Rdon Cleaning', logo: '/logos/rdoncleaning_com_logo11_nobg.png' },
  { name: 'RST Electrical', logo: '/logos/rstelectrical_co_logo5_nobg.png' },
];

export const SERVICE_OPTIONS = [
  'Google Ads Management',
  'Facebook & Meta Ads',
  'SEO Optimization',
  'Analytics & Tracking',
  'Email Marketing',
  'Conversion Optimization',
  'Full Marketing Strategy',
  'Other',
];

export const BUDGET_OPTIONS = [
  'Under $1,000',
  '$1,000 - $5,000',
  '$5,000 - $10,000',
  '$10,000 - $25,000',
  '$25,000+',
  'Not Sure',
];

export const SOCIAL_LINKS = {
  linkedin: 'https://www.linkedin.com/in/sirajul-islam-sohag-04996428a/',
  whatsapp: 'https://wa.me/8801793859694',
};

export const PORTFOLIO_CATEGORIES = [
  { value: 'all', label: 'All' },
  { value: 'google-ads', label: 'Google Ads' },
  { value: 'facebook-ads', label: 'Facebook Ads' },
  { value: 'seo', label: 'SEO' },
  { value: 'analytics', label: 'Analytics' },
  { value: 'branding', label: 'Branding' },
];
